menus_of_day:
    path:     /menus/magasin/{idmag}
    defaults: { _controller: "DominosApiBundle:Api:menus" }

get_code_to_burn:
    path:     /code/prestataire/{idpresta}
    defaults: { _controller: "DominosApiBundle:Api:getCode" }

burn_code:
    path:     /code/burn/{payload}
    defaults: { _controller: "DominosApiBundle:Api:burnCode" }

push_test:
    path:     /push
    defaults: { _controller: "DominosApiBundle:Api:push" }

client:
    path:     /client
    defaults: { _controller: "DominosApiBundle:Api:client" }