dominos_vod:
    resource: "@DominosVodBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dominos_vod_api:
    resource: "@DominosApiBundle/Resources/config/routing.yml"
    prefix:   /api