compteur:
    path:     /
    defaults: { _controller: "DominosVodBundle:Compteur:index" }

compteur_show:
    path:     /{id}/show
    defaults: { _controller: "DominosVodBundle:Compteur:show" }

compteur_new:
    path:     /new
    defaults: { _controller: "DominosVodBundle:Compteur:new" }

compteur_create:
    path:     /create
    defaults: { _controller: "DominosVodBundle:Compteur:create" }
    methods:  POST

compteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "DominosVodBundle:Compteur:edit" }

compteur_update:
    path:     /{id}/update
    defaults: { _controller: "DominosVodBundle:Compteur:update" }
    methods:  [POST, PUT]

compteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "DominosVodBundle:Compteur:delete" }
    methods:  [POST, DELETE]

compteur_index_by_presta:
    path:     /prestataire/{id}/list
    defaults: { _controller: "DominosVodBundle:CompteurPrestataire:index" }

compteur_new_by_presta:
    path:     /prestataire/new/{id}
    defaults: { _controller: "DominosVodBundle:CompteurPrestataire:new" }

compteur_create_by_presta:
    path:     /prestataire/create/{id}
    defaults: { _controller: "DominosVodBundle:CompteurPrestataire:create" }
    methods:  POST

compteur_edit_by_presta:
    path:     /prestataire/{idpresta}/edit/{id}
    defaults: { _controller: "DominosVodBundle:CompteurPrestataire:edit" }

compteur_show_by_presta:
    path:     /prestataire/{idpresta}/show/{id}
    defaults: { _controller: "DominosVodBundle:CompteurPrestataire:show" }

compteur_update_by_presta:
    path:     /prestataire/{idpresta}/update/{id}
    defaults: { _controller: "DominosVodBundle:CompteurPrestataire:update" }
    methods:  [POST, PUT]