menus:
    path:     /
    defaults: { _controller: "DominosVodBundle:Menus:index" }

menus_show:
    path:     /{id}/show
    defaults: { _controller: "DominosVodBundle:Menus:show" }

menus_new:
    path:     /new
    defaults: { _controller: "DominosVodBundle:Menus:new" }

menus_replace:
    path:     /replace
    defaults: { _controller: "DominosVodBundle:Menus:replace" }

menus_create:
    path:     /create
    defaults: { _controller: "DominosVodBundle:Menus:create" }
    methods:  POST

menus_edit:
    path:     /{id}/edit
    defaults: { _controller: "DominosVodBundle:Menus:edit" }

menus_update:
    path:     /{id}/update
    defaults: { _controller: "DominosVodBundle:Menus:update" }
    methods:  [POST, PUT]

menus_delete:
    path:     /{id}/delete
    defaults: { _controller: "DominosVodBundle:Menus:delete" }
    methods:  [POST, DELETE]
