dominos_vod_compteur:
    resource: "@DominosVodBundle/Resources/config/routing/compteur.yml"
    prefix:   /compteur

dominos_vod_prestataire:
    resource: "@DominosVodBundle/Resources/config/routing/prestataire.yml"
    prefix:   /prestataire

